# Generated by Django 2.2.6 on 2019-10-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='insert_tsd',
            field=models.DateTimeField(verbose_name='Insert Timestamp'),
        ),
    ]
