# Generated by Django 2.2.6 on 2019-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191024_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='original_url',
            field=models.URLField(default='http://test.com'),
            preserve_default=False,
        ),
    ]
