# Generated by Django 2.2.6 on 2019-11-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_article_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_tsd',
            field=models.DateTimeField(default='1990-01-01T00:00:00.000Z', verbose_name='Published at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='origin',
            field=models.CharField(choices=[('bbc', 'BBC'), ('nytimes', 'New York Times')], max_length=50),
        ),
    ]
